language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: KDI4zkHaRV33IpibduRIp7kXUlvZQdWzEO/zwt6592ri64xkzIYCpbef5/tUgQnwo3O2ITZITrOqy3OsDALynJKGFmrP/KOeSAARY17Awq61Ns1VaL2Tuf70lxJFtfgtO/jowdpT+OYbM+lcK3iH8h17OMQkeXAoVYuOKxm/6QwsLeI2DngrSFgmWhxJEnDjjVVOJ8iwYA7jm+aFCN2Hf596ndQNNZnLkjB6QsYBEXAjIDjfUYo9i39VEM0kFeCtlaupQjg+/wEVAsbKp6ZYsDqcshbd+OLphBpTwRiKQhVr33tliOFEdPkO1lXXMxYTERhID4f8z8GG+VoFj8/ExChXAehjf8H/lXkHosxF9g89t12AIjEJHaW1m5hZLDDhnJXrawDzY2gbkQAngyMVQ+fALRSW7kD1wwGuocUrRO5MYFpafM2eKsx3oJoOWEYE9NsKu/Dd95Vy70ruGhj9hv4SwwD+JWrfGsZttxBc3BU3+ZByCc5uXbughU2BlrDRUN0EaMyvdmaiXvsteCZ3qc5uf6SI3iG7Dm9prHbPMo8KaduKLAXrrBOkfBgPuBnvOw7Ti0d62GGWGFoGKY0BJT/x+aycBlq0dIoaXXqSKmKyNDBVDVcDlNiu6XfvSmF34XosIb+BVkDPYb5H+dOQONxTZU1/irXkrz3Y3iXI7Rc=
